# Use an official Python runtime as a parent image
FROM python:3.11

# Set the working directory to /customer
WORKDIR /

# Copy the current directory contents into the container at /customer
ADD . /customer.py

# Install any needed packages specified in requirements.txt
RUN apt-get update && apt-get install python3-pip -y && pip3 install fastapi


# Define environment variable
ENV Name churn

# Run customer.py when the container launches
CMD python3 customer.py